repos:
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
  - id: flake8
    name: flake8-py3
    language_version: python3
    additional_dependencies: ['flake8-bugbear==19.3.0']
  - id: flake8
    name: flake8-py2
    language_version: python2
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
  - id: isort
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.720
  hooks:
    - id: mypy
      language_version: python3
